### ISSUE TITLE
decode image failed

### ISSUE THREAD

**Issue by mlengse** [Tremeschin/dandere2x-tremx#3]
![20201018_101043](https://user-images.githubusercontent.com/11146832/96357840-f2847e00-112a-11eb-9846-3fcfcd2bdef4.jpg)
First of all, thanks for this great tools.
This message show in the console.
The process is still running though.
Any help/explanation maybe?

**Comment by Tremeschin** [comment]
Ah as far as I remember those warnings are normal, whenever we call an upscaler to upscale a input folder to an output one, it caches out all the images it have to process, whenever an image was upscaled, Python detects that and deletes that respective image on the input folder, however there is a slight chance it was the last image the upscaler was going to process so we call the upscaler immediately after as the input folder will have new files, in this process what is happening is that, from that previous batch the upscaler had just finished that image and started again, so that image is still there and after the upscaler was called, python deletes that image as it was processed on the previous batch, yielding decode error because the image does not exist.

**Comment by Tremeschin** [comment]
Btw this Dandere2x version of mine is half abandoned :( wouldn't say it is dead but past months and next few months I'll be focusing on my other project [MMV](https://github.com/Tremeschin/modular-music-visualizer), just saying this so don't expect many more new features or changes here unless those are very very critical, dandere2x-tremx had got to a point it was usable (for me) before I moved my efforts to this other project.

Thanks you tried it, appreciate your interest in such niche project!!
